# Uncomment the next line to define a global platform for your project
platform :macos
source 'https://cdn.cocoapods.org/'
target 'iOSWorkflow' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Yams'
  # Pods for iOSWorkflow

end
